package com.leigh.peaksandtalons.entity;

import com.leigh.peaksandtalons.registry.ModEntities;import com.leigh.peaksandtalons.registry.ModItems;import net.minecraft.core.BlockPos;import net.minecraft.nbt.CompoundTag;import net.minecraft.network.chat.Component;import net.minecraft.server.level.*;import net.minecraft.world.*;import net.minecraft.world.damagesource.DamageSource;import net.minecraft.world.entity.*;import net.minecraft.world.entity.ai.attributes.*;import net.minecraft.world.entity.ai.control.FlyingMoveControl;import net.minecraft.world.entity.ai.goal.*;import net.minecraft.world.entity.ai.goal.target.*;import net.minecraft.world.entity.ai.navigation.*;import net.minecraft.world.entity.player.Player;import net.minecraft.world.item.*;import net.minecraft.world.level.Level;import net.minecraft.world.phys.Vec3;import org.jetbrains.annotations.Nullable;import java.util.*;
public class EagleEntity extends TamableAnimal{
 public enum BehaviorMode{STAY,FOLLOW,WANDER} private boolean saddled,vengeanceSpawned,trustReady;private int attackAnimationTicks,tameProgress,tamingRideTicks,tamingGoalTicks;private double tamingStartY;private BehaviorMode behaviorMode=BehaviorMode.FOLLOW;private ServerBossEvent encounterBar;private List<EagleEntity> encounterMembers=new ArrayList<>();
 public EagleEntity(EntityType<? extends EagleEntity> t,Level l){super(t,l);moveControl=new FlyingMoveControl(this,24,true);encounterBar=new ServerBossEvent(Component.literal("Eagle"),BossEvent.BossBarColor.YELLOW,BossEvent.BossBarOverlay.PROGRESS);}public static AttributeSupplier.Builder attributes(){return LivingEntity.createLivingAttributes().add(Attributes.MAX_HEALTH,36).add(Attributes.MOVEMENT_SPEED,.40).add(Attributes.FLYING_SPEED,1.0).add(Attributes.ATTACK_DAMAGE,8).add(Attributes.FOLLOW_RANGE,56);}@Override protected PathNavigation createNavigation(Level l){FlyingPathNavigation n=new FlyingPathNavigation(this,l);n.setCanFloat(true);return n;}
 @Override protected void registerGoals(){goalSelector.addGoal(0,new FloatGoal(this));goalSelector.addGoal(1,new SitWhenOrderedToGoal(this));goalSelector.addGoal(2,new MeleeAttackGoal(this,1.8,true));goalSelector.addGoal(3,new FollowOwnerGoal(this,1.45,7,2){public boolean canUse(){return behaviorMode==BehaviorMode.FOLLOW&&super.canUse();}public boolean canContinueToUse(){return behaviorMode==BehaviorMode.FOLLOW&&super.canContinueToUse();}});goalSelector.addGoal(4,new WaterAvoidingRandomFlyingGoal(this,1.25){public boolean canUse(){return(!isTame()||behaviorMode==BehaviorMode.WANDER)&&super.canUse();}});goalSelector.addGoal(5,new LookAtPlayerGoal(this,Player.class,16));targetSelector.addGoal(1,new HurtByTargetGoal(this).setAlertOthers(EagleEntity.class));targetSelector.addGoal(2,new NearestAttackableTargetGoal<>(this,Player.class,10,true,false,p->vengeanceSpawned&&!isTame()));}
 public int getAttackAnimationTicks(){return attackAnimationTicks;}public boolean isSaddled(){return saddled;}@Override public boolean isFood(ItemStack s){return s.is(Items.SALMON);}@Override public boolean doHurtTarget(Entity t){attackAnimationTicks=12;return super.doHurtTarget(t);}
 @Override public InteractionResult mobInteract(Player p,InteractionHand h){ItemStack s=p.getItemInHand(h);if(!isTame()&&s.is(Items.SALMON)){if(!p.getAbilities().instabuild)s.shrink(1);trustReady=true;return InteractionResult.sidedSuccess(level().isClientSide);}if(!isTame()&&trustReady&&s.isEmpty()){if(!level().isClientSide){tamingRideTicks=0;tamingGoalTicks=100+random.nextInt(81);tamingStartY=getY();p.startRiding(this,true);}return InteractionResult.sidedSuccess(level().isClientSide);}if(isTame()&&isOwnedBy(p)&&s.is(Items.STICK)){if(!level().isClientSide){behaviorMode=switch(behaviorMode){case STAY->BehaviorMode.FOLLOW;case FOLLOW->BehaviorMode.WANDER;case WANDER->BehaviorMode.STAY;};setOrderedToSit(behaviorMode==BehaviorMode.STAY);p.displayClientMessage(Component.literal("Eagle: "+behaviorMode.name().toLowerCase()),true);}return InteractionResult.sidedSuccess(level().isClientSide);}if(isTame()&&isOwnedBy(p)&&!saddled&&s.is(Items.SADDLE)){saddled=true;if(!p.getAbilities().instabuild)s.shrink(1);return InteractionResult.sidedSuccess(level().isClientSide);}if(isTame()&&isOwnedBy(p)&&saddled&&!p.isShiftKeyDown()){if(!level().isClientSide)p.startRiding(this,true);return InteractionResult.sidedSuccess(level().isClientSide);}return super.mobInteract(p,h);}
 @Override public void tick(){super.tick();if(attackAnimationTicks>0)attackAnimationTicks--;if(!isTame()&&trustReady&&isVehicle()&&getFirstPassenger()instanceof Player r){tamingRideTicks++;setNoGravity(true);setDeltaMovement(getDeltaMovement().scale(.75).add(0,.1,0));if(tamingRideTicks>=tamingGoalTicks){tameProgress++;trustReady=false;ejectPassengers();setNoGravity(false);if(tameProgress>=2+random.nextInt(3)){tame(r);if(!r.addItem(new ItemStack(ModItems.EYE_OF_THE_EAGLE.get())))spawnAtLocation(ModItems.EYE_OF_THE_EAGLE.get());}}}else setNoGravity(saddled&&isVehicle());updateBossBar();}
 @Override public void travel(Vec3 in){LivingEntity r=getControllingPassenger();if(isTame()&&saddled&&r instanceof Player p){setYRot(p.getYRot());setXRot(p.getXRot()*.35F);float f=p.zza,st=p.xxa*.45F;double speed=getAttributeValue(Attributes.FLYING_SPEED);double yaw=Math.toRadians(p.getYRot());Vec3 forward=new Vec3(-Math.sin(yaw),0,Math.cos(yaw));Vec3 side=new Vec3(Math.cos(yaw),0,Math.sin(yaw));Vec3 desired=forward.scale(f*speed).add(side.scale(st*speed));double lookLift=-Math.sin(Math.toRadians(p.getXRot()))*.38;double y=onGround()?Math.max(0,lookLift):Math.max(-.16,getDeltaMovement().y-.018+lookLift*.16);if(p.isShiftKeyDown())y=-.32;desired=new Vec3(desired.x,y,desired.z);setDeltaMovement(getDeltaMovement().scale(.52).add(desired.scale(.48)));move(MoverType.SELF,getDeltaMovement());fallDistance=0;return;}super.travel(in);}
 private void updateBossBar(){if(!(level()instanceof ServerLevel s)||isTame())return;float hp=getHealth(),max=getMaxHealth();if(!encounterMembers.isEmpty()){hp=0;max=0;for(EagleEntity e:encounterMembers){max+=e.getMaxHealth();if(e.isAlive())hp+=e.getHealth();}}encounterBar.setProgress(max<=0?0:hp/max);for(ServerPlayer p:s.players())if(distanceToSqr(p)<4096)encounterBar.addPlayer(p);else encounterBar.removePlayer(p);}
 private void startVengeanceStorm(ServerLevel s){s.setWeatherParameters(0,1800,true,true);for(int i=0;i<4;i++){LightningBolt b=EntityType.LIGHTNING_BOLT.create(s);if(b!=null){double a=Math.PI*2*i/4,r=10+random.nextInt(12);b.moveTo(Vec3.atBottomCenterOf(BlockPos.containing(getX()+Math.cos(a)*r,getY(),getZ()+Math.sin(a)*r)));b.setVisualOnly(true);s.addFreshEntity(b);}}}
 @Override public void die(DamageSource src){boolean phase=!isTame()&&!vengeanceSpawned&&!level().isClientSide;LivingEntity k=src.getEntity()instanceof LivingEntity l?l:null;super.die(src);if(phase&&level()instanceof ServerLevel s){startVengeanceStorm(s);encounterMembers=new ArrayList<>();for(int i=0;i<3;i++){EagleEntity e=ModEntities.EAGLE.get().create(s);if(e!=null){e.vengeanceSpawned=true;e.encounterBar=encounterBar;e.encounterMembers=encounterMembers;e.moveTo(getX()+random.nextInt(9)-4,getY()+7,getZ()+random.nextInt(9)-4,0,0);encounterMembers.add(e);s.addFreshEntity(e);if(k!=null)e.setTarget(k);}}encounterBar.setProgress(1);encounterBar.setName(Component.literal("Eagle — Vengeance"));}}
 @Nullable public LivingEntity getControllingPassenger(){return getFirstPassenger()instanceof LivingEntity l?l:null;}protected boolean canAddPassenger(Entity p){return getPassengers().isEmpty()&&p instanceof Player;}public void addAdditionalSaveData(CompoundTag t){super.addAdditionalSaveData(t);t.putBoolean("Saddled",saddled);t.putInt("TameProgress",tameProgress);t.putString("BehaviorMode",behaviorMode.name());}public void readAdditionalSaveData(CompoundTag t){super.readAdditionalSaveData(t);saddled=t.getBoolean("Saddled");tameProgress=t.getInt("TameProgress");try{behaviorMode=BehaviorMode.valueOf(t.getString("BehaviorMode"));}catch(Exception x){behaviorMode=BehaviorMode.FOLLOW;}}@Nullable public EagleEntity getBreedOffspring(ServerLevel l,AgeableMob o){return ModEntities.EAGLE.get().create(l);}
}
