package com.leigh.peaksandtalons.entity;

import com.leigh.peaksandtalons.registry.ModEntities;
import com.leigh.peaksandtalons.registry.ModItems;
import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.*;
import net.minecraft.world.*;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.*;
import net.minecraft.world.entity.ai.control.FlyingMoveControl;
import net.minecraft.world.entity.ai.goal.*;
import net.minecraft.world.entity.ai.goal.target.*;
import net.minecraft.world.entity.ai.navigation.*;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.AbstractContainerMenu;
import net.minecraft.world.inventory.ChestMenu;
import net.minecraft.world.inventory.MenuType;
import net.minecraft.world.item.*;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;
import org.jetbrains.annotations.Nullable;
import java.util.*;

public class EagleEntity extends TamableAnimal {
 public enum BehaviorMode { STAY, FOLLOW, WANDER }
 private boolean harnessed,vengeanceSpawned,trustReady;
 private int attackAnimationTicks,tameProgress,tamingRideTicks,tamingGoalTicks;
 private double tamingStartY;
 private BehaviorMode behaviorMode=BehaviorMode.FOLLOW;
 private ServerBossEvent encounterBar;
 private List<EagleEntity> encounterMembers=new ArrayList<>();
 private final SimpleContainer harnessInventory=new SimpleContainer(9);
 public EagleEntity(EntityType<? extends EagleEntity> t,Level l){super(t,l);moveControl=new FlyingMoveControl(this,45,true);encounterBar=new ServerBossEvent(Component.literal("Eagle"),BossEvent.BossBarColor.YELLOW,BossEvent.BossBarOverlay.PROGRESS);}
 public static AttributeSupplier.Builder attributes(){return LivingEntity.createLivingAttributes().add(Attributes.MAX_HEALTH,52).add(Attributes.MOVEMENT_SPEED,.56).add(Attributes.FLYING_SPEED,1.55).add(Attributes.ATTACK_DAMAGE,10).add(Attributes.FOLLOW_RANGE,96).add(Attributes.KNOCKBACK_RESISTANCE,.35);}
 @Override protected PathNavigation createNavigation(Level l){FlyingPathNavigation n=new FlyingPathNavigation(this,l);n.setCanFloat(true);return n;}
 @Override protected void registerGoals(){goalSelector.addGoal(0,new FloatGoal(this));goalSelector.addGoal(1,new SitWhenOrderedToGoal(this));goalSelector.addGoal(2,new VengeanceDiveGoal());goalSelector.addGoal(3,new MeleeAttackGoal(this,2.25,true));goalSelector.addGoal(4,new FollowOwnerGoal(this,1.55,7,2){public boolean canUse(){return behaviorMode==BehaviorMode.FOLLOW&&super.canUse();}public boolean canContinueToUse(){return behaviorMode==BehaviorMode.FOLLOW&&super.canContinueToUse();}});goalSelector.addGoal(5,new WaterAvoidingRandomFlyingGoal(this,1.6){public boolean canUse(){return(!isTame()||behaviorMode==BehaviorMode.WANDER)&&super.canUse();}});goalSelector.addGoal(6,new LookAtPlayerGoal(this,Player.class,24));targetSelector.addGoal(1,new HurtByTargetGoal(this).setAlertOthers(EagleEntity.class));targetSelector.addGoal(2,new NearestAttackableTargetGoal<>(this,Player.class,2,true,false,p->!isTame()&&(vengeanceSpawned||!trustReady)));}
 private class VengeanceDiveGoal extends Goal{private int cooldown;VengeanceDiveGoal(){setFlags(EnumSet.of(Flag.MOVE,Flag.LOOK));}public boolean canUse(){LivingEntity t=getTarget();return vengeanceSpawned&&!isTame()&&t!=null&&t.isAlive();}public boolean canContinueToUse(){return canUse();}public void start(){cooldown=5+random.nextInt(8);setNoGravity(true);}public void stop(){if(!isVehicle())setNoGravity(false);}public void tick(){LivingEntity t=getTarget();if(t==null)return;getLookControl().setLookAt(t,60,60);double d=distanceToSqr(t);Vec3 tp=t.position();if(d>36){double angle=(tickCount*.23)+(getId()%9);double radius=d>324?4.5:2.0;double y=tp.y+Math.min(10,3+Math.sqrt(d)*.10);getNavigation().moveTo(tp.x+Math.cos(angle)*radius,y,tp.z+Math.sin(angle)*radius,2.85);}else{getNavigation().moveTo(tp.x,tp.y+t.getBbHeight()*.55,tp.z,3.35);Vec3 dive=tp.add(0,t.getBbHeight()*.45,0).subtract(position()).normalize().scale(.48);setDeltaMovement(getDeltaMovement().scale(.68).add(dive));}if(cooldown>0)cooldown--;if(d<=25&&cooldown<=0&&hasLineOfSight(t)){doHurtTarget(t);cooldown=14+random.nextInt(8);Vec3 pass=t.position().subtract(position()).normalize().scale(1.35);setDeltaMovement(getDeltaMovement().add(pass.x,.28,pass.z));}}}
 private static void award(ServerPlayer p,String path){AdvancementHolder a=p.server.getAdvancements().get(ResourceLocation.fromNamespaceAndPath("peaksandtalons",path));if(a==null)return;var progress=p.getAdvancements().getOrStartProgress(a);for(String criterion:progress.getRemainingCriteria())p.getAdvancements().award(a,criterion);}
 public int getAttackAnimationTicks(){return attackAnimationTicks;} public boolean isSaddled(){return harnessed;} public boolean isHarnessed(){return harnessed;}
 @Override public boolean isFood(ItemStack s){return s.is(Items.SALMON);}
 @Override public boolean doHurtTarget(Entity t){attackAnimationTicks=12;boolean hit=super.doHurtTarget(t);if(hit&&t instanceof LivingEntity l){Vec3 v=l.position().subtract(position()).normalize().scale(.85);l.push(v.x,.3,v.z);}return hit;}
 private void openHarnessInventory(ServerPlayer player){player.openMenu(new MenuProvider(){public Component getDisplayName(){return Component.literal("Golden Eagle Harness");}public AbstractContainerMenu createMenu(int id,Inventory inv,Player p){return new ChestMenu(MenuType.GENERIC_9x1,id,inv,harnessInventory,1);}});}
 @Override public InteractionResult mobInteract(Player p,InteractionHand h){ItemStack s=p.getItemInHand(h);if(!isTame()&&s.is(Items.SALMON)){if(!p.getAbilities().instabuild)s.shrink(1);trustReady=true;setTarget(null);getNavigation().stop();if(!level().isClientSide){level().broadcastEntityEvent(this,(byte)7);p.displayClientMessage(Component.literal("The Eagle accepts the salmon. Mount it with an empty hand and prove your bond."),true);if(p instanceof ServerPlayer sp)award(sp,"eagle/bond_path");}return InteractionResult.sidedSuccess(level().isClientSide);}if(!isTame()&&trustReady&&s.isEmpty()){if(!level().isClientSide){tamingRideTicks=0;tamingGoalTicks=150+random.nextInt(51);tamingStartY=getY();p.startRiding(this,true);}return InteractionResult.sidedSuccess(level().isClientSide);}if(isTame()&&isOwnedBy(p)&&s.is(Items.STICK)){if(!level().isClientSide){behaviorMode=switch(behaviorMode){case STAY->BehaviorMode.FOLLOW;case FOLLOW->BehaviorMode.WANDER;case WANDER->BehaviorMode.STAY;};setOrderedToSit(behaviorMode==BehaviorMode.STAY);p.displayClientMessage(Component.literal("Eagle: "+behaviorMode.name().toLowerCase()),true);}return InteractionResult.sidedSuccess(level().isClientSide);}if(isTame()&&isOwnedBy(p)&&!harnessed&&s.is(ModItems.GOLDEN_EAGLE_HARNESS.get())){harnessed=true;if(!p.getAbilities().instabuild)s.shrink(1);if(!level().isClientSide)p.displayClientMessage(Component.literal("Golden Eagle Harness equipped. Sneak + interact to open its 9-slot pack."),true);return InteractionResult.sidedSuccess(level().isClientSide);}if(isTame()&&isOwnedBy(p)&&harnessed&&p.isShiftKeyDown()){if(!level().isClientSide&&p instanceof ServerPlayer sp)openHarnessInventory(sp);return InteractionResult.sidedSuccess(level().isClientSide);}if(isTame()&&isOwnedBy(p)&&harnessed&&!p.isShiftKeyDown()){if(!level().isClientSide){p.startRiding(this,true);if(p instanceof ServerPlayer sp)award(sp,"eagle/first_flight");}return InteractionResult.sidedSuccess(level().isClientSide);}return super.mobInteract(p,h);}
 @Override public void tick(){super.tick();if(attackAnimationTicks>0)attackAnimationTicks--;if(vengeanceSpawned&&!isTame()){setNoGravity(true);if((getTarget()==null||!getTarget().isAlive())&&tickCount%10==0){Player nearest=level().getNearestPlayer(this,96);if(nearest!=null&&!nearest.isSpectator())setTarget(nearest);}if(getTarget()!=null&&tickCount%20==0&&getNavigation().isDone()){LivingEntity t=getTarget();getNavigation().moveTo(t.getX(),t.getY()+4,t.getZ(),2.8);}}if(!isTame()&&trustReady&&isVehicle()&&getFirstPassenger()instanceof Player r){tamingRideTicks++;setNoGravity(true);fallDistance=0;double phase=tamingRideTicks*.105;double rise=getY()-tamingStartY;double climb=rise<14?.16:(Math.sin(phase*.31)*.09);double surge=.14+Math.min(.16,tamingRideTicks/900D);Vec3 flight=new Vec3(Math.cos(phase)*surge,climb,Math.sin(phase)*surge);if(tamingRideTicks%85<9)flight=flight.add(0,-.15,0);setDeltaMovement(getDeltaMovement().scale(.52).add(flight));move(MoverType.SELF,getDeltaMovement());if(tamingRideTicks>120&&tamingRideTicks%120==0&&random.nextFloat()<.06F){ejectPassengers();setNoGravity(false);trustReady=true;level().broadcastEntityEvent(this,(byte)6);r.displayClientMessage(Component.literal("The Eagle throws you, but does not reject you. Mount again while its trust holds."),true);return;}if(tamingRideTicks>=tamingGoalTicks){tameProgress++;trustReady=false;ejectPassengers();setNoGravity(false);if(tameProgress>=2){tame(r);behaviorMode=BehaviorMode.FOLLOW;level().broadcastEntityEvent(this,(byte)7);if(r instanceof ServerPlayer sp)award(sp,"eagle/tamed");if(!r.addItem(new ItemStack(ModItems.EYE_OF_THE_EAGLE.get())))spawnAtLocation(ModItems.EYE_OF_THE_EAGLE.get());}else{level().broadcastEntityEvent(this,(byte)7);r.displayClientMessage(Component.literal("The Eagle is beginning to trust you. Offer another salmon to attempt the final trial."),true);}}}else if(!vengeanceSpawned)setNoGravity(harnessed&&isVehicle());updateBossBar();}
 @Override public void travel(Vec3 in){LivingEntity r=getControllingPassenger();if(isTame()&&harnessed&&r instanceof Player p){setYRot(p.getYRot());setXRot(p.getXRot()*.35F);float f=p.zza,st=p.xxa*.45F;double speed=getAttributeValue(Attributes.FLYING_SPEED);double yaw=Math.toRadians(p.getYRot());Vec3 forward=new Vec3(-Math.sin(yaw),0,Math.cos(yaw));Vec3 side=new Vec3(Math.cos(yaw),0,Math.sin(yaw));Vec3 desired=forward.scale(f*speed).add(side.scale(st*speed));double lookLift=-Math.sin(Math.toRadians(p.getXRot()))*.38;double y=onGround()?Math.max(0,lookLift):Math.max(-.16,getDeltaMovement().y-.018+lookLift*.16);if(p.isShiftKeyDown())y=-.32;desired=new Vec3(desired.x,y,desired.z);setDeltaMovement(getDeltaMovement().scale(.52).add(desired.scale(.48)));move(MoverType.SELF,getDeltaMovement());fallDistance=0;return;}super.travel(in);}
 private void updateBossBar(){if(!(level()instanceof ServerLevel s)||isTame())return;float hp=getHealth(),max=getMaxHealth();if(!encounterMembers.isEmpty()){hp=0;max=0;for(EagleEntity e:encounterMembers){max+=e.getMaxHealth();if(e.isAlive())hp+=e.getHealth();}}encounterBar.setProgress(max<=0?0:hp/max);for(ServerPlayer p:s.players())if(distanceToSqr(p)<9216)encounterBar.addPlayer(p);else encounterBar.removePlayer(p);}
 private void startVengeanceStorm(ServerLevel s){s.setWeatherParameters(0,2400,true,true);for(int i=0;i<4;i++){LightningBolt b=EntityType.LIGHTNING_BOLT.create(s);if(b!=null){double a=Math.PI*2*i/4,r=10+random.nextInt(12);b.moveTo(Vec3.atBottomCenterOf(BlockPos.containing(getX()+Math.cos(a)*r,getY(),getZ()+Math.sin(a)*r)));b.setVisualOnly(true);s.addFreshEntity(b);}}}
 @Override public void die(DamageSource src){boolean phase=!isTame()&&!vengeanceSpawned&&!level().isClientSide;boolean vengeance=vengeanceSpawned&&!level().isClientSide;LivingEntity k=src.getEntity()instanceof LivingEntity l?l:null;super.die(src);if(vengeance&&level()instanceof ServerLevel s){boolean anyAlive=false;for(EagleEntity e:encounterMembers)if(e!=this&&e.isAlive()){anyAlive=true;break;}if(!anyAlive){encounterBar.setProgress(0);encounterBar.setVisible(false);if(k instanceof ServerPlayer sp)award(sp,"eagle/vengeance_defeated");else{Player nearby=s.getNearestPlayer(getX(),getY(),getZ(),96,false);if(nearby instanceof ServerPlayer sp)award(sp,"eagle/vengeance_defeated");}}}if(phase&&level()instanceof ServerLevel s){startVengeanceStorm(s);encounterMembers=new ArrayList<>();Player fallback=k instanceof Player p?p:s.getNearestPlayer(getX(),getY(),getZ(),96,false);for(int i=0;i<3;i++){EagleEntity e=ModEntities.EAGLE.get().create(s);if(e!=null){e.vengeanceSpawned=true;e.encounterBar=encounterBar;e.encounterMembers=encounterMembers;e.setNoGravity(true);e.moveTo(getX()+random.nextInt(13)-6,getY()+12+random.nextInt(8),getZ()+random.nextInt(13)-6,0,0);encounterMembers.add(e);s.addFreshEntity(e);if(k!=null)e.setTarget(k);else if(fallback!=null)e.setTarget(fallback);}}encounterBar.setProgress(1);encounterBar.setName(Component.literal("Eagle — Vengeance"));}}
 @Nullable public LivingEntity getControllingPassenger(){return getFirstPassenger()instanceof LivingEntity l?l:null;}
 protected boolean canAddPassenger(Entity p){return getPassengers().isEmpty()&&p instanceof Player;}
 public void addAdditionalSaveData(CompoundTag t){super.addAdditionalSaveData(t);t.putBoolean("Harnessed",harnessed);t.putBoolean("VengeanceSpawned",vengeanceSpawned);t.putInt("TameProgress",tameProgress);t.putBoolean("TrustReady",trustReady);t.putString("BehaviorMode",behaviorMode.name());t.put("HarnessInventory",harnessInventory.createTag(registryAccess()));}
 public void readAdditionalSaveData(CompoundTag t){super.readAdditionalSaveData(t);harnessed=t.getBoolean("Harnessed")||t.getBoolean("Saddled");vengeanceSpawned=t.getBoolean("VengeanceSpawned");tameProgress=t.getInt("TameProgress");trustReady=t.getBoolean("TrustReady");try{behaviorMode=BehaviorMode.valueOf(t.getString("BehaviorMode"));}catch(Exception x){behaviorMode=BehaviorMode.FOLLOW;}if(t.contains("HarnessInventory"))harnessInventory.fromTag(t.getList("HarnessInventory",10),registryAccess());}
 @Nullable public EagleEntity getBreedOffspring(ServerLevel l,AgeableMob o){return ModEntities.EAGLE.get().create(l);}
}
